import React from 'react';
import { Pie, Bar } from 'react-chartjs-2';
import {
  Chart as ChartJS,
    CategoryScale,
      LinearScale,
        BarElement,
          ArcElement,
            Title,
              Tooltip,
                Legend
                } from 'chart.js';

                ChartJS.register(
                  CategoryScale,
                    LinearScale,
                      BarElement,
                        ArcElement,
                          Title,
                            Tooltip,
                              Legend
                              );

                              const Charts = ({ expenses }) => {
                                const categoryTotals = expenses.reduce((acc, expense) => {
                                    acc[expense.category] = (acc[expense.category] || 0) + expense.amount;
                                        return acc;
                                          }, {});

                                            const pieData = {
                                                labels: Object.keys(categoryTotals),
                                                    datasets: [
                                                          {
                                                                  data: Object.values(categoryTotals),
                                                                          backgroundColor: [
                                                                                    '#FF6384', '#36A2EB', '#FFCE56', '#4BC0C0',
                                                                                              '#9966FF', '#FF9F40', '#FF6384', '#C9CBCF', '#4BC0C0'
                                                                                                      ],
                                                                                                              borderWidth: 2,
                                                                                                                      borderColor: '#fff'
                                                                                                                            }
                                                                                                                                ]
                                                                                                                                  };

                                                                                                                                    const barData = {
                                                                                                                                        labels: Object.keys(categoryTotals),
                                                                                                                                            datasets: [
                                                                                                                                                  {
                                                                                                                                                          label: 'Spending by Category',
                                                                                                                                                                  data: Object.values(categoryTotals),
                                                                                                                                                                          backgroundColor: 'rgba(102, 126, 234, 0.8)',
                                                                                                                                                                                  borderColor: 'rgba(102, 126, 234, 1)',
                                                                                                                                                                                          borderWidth: 2,
                                                                                                                                                                                                  borderRadius: 5
                                                                                                                                                                                                        }
                                                                                                                                                                                                            ]
                                                                                                                                                                                                              };

                                                                                                                                                                                                                const chartOptions = {
                                                                                                                                                                                                                    responsive: true,
                                                                                                                                                                                                                        maintainAspectRatio: false,
                                                                                                                                                                                                                            plugins: {
                                                                                                                                                                                                                                  legend: {
                                                                                                                                                                                                                                          position: 'bottom'
                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                        const barOptions = {
                                                                                                                                                                                                                                                            ...chartOptions,
                                                                                                                                                                                                                                                                scales: {
                                                                                                                                                                                                                                                                      y: {
                                                                                                                                                                                                                                                                              beginAtZero: true,
                                                                                                                                                                                                                                                                                      ticks: {
                                                                                                                                                                                                                                                                                                callback: function(value) {
                                                                                                                                                                                                                                                                                                            return '$' + value;
                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                                                                            if (expenses.length === 0) {
                                                                                                                                                                                                                                                                                                                                                return (
                                                                                                                                                                                                                                                                                                                                                      <div className="card">
                                                                                                                                                                                                                                                                                                                                                              <h2>Spending Charts</h2>
                                                                                                                                                                                                                                                                                                                                                                      <div className="empty-state">
                                                                                                                                                                                                                                                                                                                                                                                <p>Add some expenses to see your spending charts!</p>
                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                      return (
                                                                                                                                                                                                                                                                                                                                                                                                          <div className="card">
                                                                                                                                                                                                                                                                                                                                                                                                                <h2>Spending Charts</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{ display: 'grid', gridTemplateColumns: '1fr', gap: '30px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                        <h3 style={{ textAlign: 'center', marginBottom: '15px', color: '#555' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    Spending Distribution
                                                                                                                                                                                                                                                                                                                                                                                                                                                              </h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="chart-container">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Pie data={pieData} options={chartOptions} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h3 style={{ textAlign: 'center', marginBottom: '15px', color: '#555' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Category Comparison
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="chart-container">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Bar data={barData} options={barOptions} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          export default Charts;