import React from 'react';

const Dashboard = ({ expenses }) => {
  const totalExpenses = expenses.reduce((sum, expense) => sum + expense.amount, 0);
    
      const categoryTotals = expenses.reduce((acc, expense) => {
          acc[expense.category] = (acc[expense.category] || 0) + expense.amount;
              return acc;
                }, {});

                  const topCategory = Object.entries(categoryTotals).reduce(
                      (top, [category, amount]) => amount > (top.amount || 0) ? { category, amount } : top,
                          {}
                            );

                              return (
                                  <div className="card">
                                        <h2>Financial Overview</h2>
                                              
                                                    <div className="stats-grid">
                                                            <div className="stat-card">
                                                                      <h3>Total Expenses</h3>
                                                                                <div className="amount">${totalExpenses.toFixed(2)}</div>
                                                                                        </div>
                                                                                                
                                                                                                        <div className="stat-card">
                                                                                                                  <h3>Number of Expenses</h3>
                                                                                                                            <div className="amount">{expenses.length}</div>
                                                                                                                                    </div>
                                                                                                                                            
                                                                                                                                                    <div className="stat-card">
                                                                                                                                                              <h3>Average per Expense</h3>
                                                                                                                                                                        <div className="amount">
                                                                                                                                                                                    ${expenses.length > 0 ? (totalExpenses / expenses.length).toFixed(2) : '0.00'}
                                                                                                                                                                                              </div>
                                                                                                                                                                                                      </div>
                                                                                                                                                                                                              
                                                                                                                                                                                                                      <div className="stat-card">
                                                                                                                                                                                                                                <h3>Top Category</h3>
                                                                                                                                                                                                                                          <div className="amount">
                                                                                                                                                                                                                                                      {topCategory.category || 'N/A'}
                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                          {topCategory.amount && (
                                                                                                                                                                                                                                                                                      <small>${topCategory.amount.toFixed(2)}</small>
                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                    {/* Category Breakdown */}
                                                                                                                                                                                                                                                                                                                          <div style={{ marginTop: '20px' }}>
                                                                                                                                                                                                                                                                                                                                  <h3 style={{ marginBottom: '15px', color: '#555' }}>Spending by Category</h3>
                                                                                                                                                                                                                                                                                                                                          {Object.entries(categoryTotals).length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                    <p style={{ textAlign: 'center', color: '#666', fontStyle: 'italic' }}>
                                                                                                                                                                                                                                                                                                                                                                No category data available
                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                  ) : (
                                                                                                                                                                                                                                                                                                                                                                                            <div style={{ display: 'grid', gap: '10px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                        {Object.entries(categoryTotals)
                                                                                                                                                                                                                                                                                                                                                                                                                      .sort(([,a], [,b]) => b - a)
                                                                                                                                                                                                                                                                                                                                                                                                                                    .map(([category, amount]) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div key={category} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span style={{ fontWeight: '500' }}>{category}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={{ 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  width: '100px', 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        height: '8px', 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              backgroundColor: '#e1e5e9',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    borderRadius: '4px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          overflow: 'hidden'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      width: `${(amount / totalExpenses) * 100}%`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                height: '100%',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    borderRadius: '4px'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span style={{ fontWeight: 'bold', minWidth: '70px', textAlign: 'right' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ${amount.toFixed(2)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  export default Dashboard;