import React, { useState, useEffect } from 'react';

const ExpenseForm = ({ expense, onSave, onCancel }) => {
  const [formData, setFormData] = useState({
      amount: '',
          category: '',
              date: new Date().toISOString().split('T')[0],
                  description: ''
                    });

                      const categories = [
                          'Food & Dining',
                              'Transportation',
                                  'Shopping',
                                      'Entertainment',
                                          'Bills & Utilities',
                                              'Healthcare',
                                                  'Travel',
                                                      'Education',
                                                          'Other'
                                                            ];

                                                              useEffect(() => {
                                                                  if (expense) {
                                                                        setFormData({
                                                                                amount: expense.amount,
                                                                                        category: expense.category,
                                                                                                date: expense.date,
                                                                                                        description: expense.description
                                                                                                              });
                                                                                                                  }
                                                                                                                    }, [expense]);

                                                                                                                      const handleChange = (e) => {
                                                                                                                          setFormData({
                                                                                                                                ...formData,
                                                                                                                                      [e.target.name]: e.target.value
                                                                                                                                          });
                                                                                                                                            };

                                                                                                                                              const handleSubmit = (e) => {
                                                                                                                                                  e.preventDefault();
                                                                                                                                                      if (!formData.amount || !formData.category) {
                                                                                                                                                            alert('Please fill in all required fields');
                                                                                                                                                                  return;
                                                                                                                                                                      }

                                                                                                                                                                          onSave({
                                                                                                                                                                                ...formData,
                                                                                                                                                                                      amount: parseFloat(formData.amount)
                                                                                                                                                                                          });

                                                                                                                                                                                              if (!expense) {
                                                                                                                                                                                                    setFormData({
                                                                                                                                                                                                            amount: '',
                                                                                                                                                                                                                    category: '',
                                                                                                                                                                                                                            date: new Date().toISOString().split('T')[0],
                                                                                                                                                                                                                                    description: ''
                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                  return (
                                                                                                                                                                                                                                                      <div className="card">
                                                                                                                                                                                                                                                            <h2>{expense ? 'Edit Expense' : 'Add New Expense'}</h2>
                                                                                                                                                                                                                                                                  <form onSubmit={handleSubmit}>
                                                                                                                                                                                                                                                                          <div className="form-group">
                                                                                                                                                                                                                                                                                    <label htmlFor="amount">Amount ($)*</label>
                                                                                                                                                                                                                                                                                              <input
                                                                                                                                                                                                                                                                                                          type="number"
                                                                                                                                                                                                                                                                                                                      id="amount"
                                                                                                                                                                                                                                                                                                                                  name="amount"
                                                                                                                                                                                                                                                                                                                                              value={formData.amount}
                                                                                                                                                                                                                                                                                                                                                          onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                      step="0.01"
                                                                                                                                                                                                                                                                                                                                                                                  min="0"
                                                                                                                                                                                                                                                                                                                                                                                              required
                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="form-group">
                                                                                                                                                                                                                                                                                                                                                                                                                                  <label htmlFor="category">Category*</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                            <select
                                                                                                                                                                                                                                                                                                                                                                                                                                                        id="category"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    name="category"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                value={formData.category}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <option value="">Select a category</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {categories.map(category => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <option key={category} value={category}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {category}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="form-group">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <label htmlFor="date">Date</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            type="date"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        id="date"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    name="date"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                value={formData.date}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="form-group">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <label htmlFor="description">Description</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <textarea
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      id="description"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  name="description"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              value={formData.description}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      placeholder="Add a description for this expense..."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div style={{ display: 'flex', gap: '10px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button type="submit" className="btn">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {expense ? 'Update Expense' : 'Add Expense'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {expense && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button type="button" className="btn btn-danger" onClick={onCancel}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Cancel
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              export default ExpenseForm;