import React from 'react';

const ExpenseList = ({ expenses, onEdit, onDelete, filters, onFilterChange, sortBy, onSortChange }) => {
  const categories = [
      'Food & Dining',
          'Transportation',
              'Shopping',
                  'Entertainment',
                      'Bills & Utilities',
                          'Healthcare',
                              'Travel',
                                  'Education',
                                      'Other'
                                        ];

                                          const filteredExpenses = expenses
                                              .filter(expense => {
                                                    if (filters.category && expense.category !== filters.category) return false;
                                                          if (filters.startDate && expense.date < filters.startDate) return false;
                                                                if (filters.endDate && expense.date > filters.endDate) return false;
                                                                      return true;
                                                                          })
                                                                              .sort((a, b) => {
                                                                                    switch (sortBy) {
                                                                                            case 'amount-desc':
                                                                                                      return b.amount - a.amount;
                                                                                                              case 'amount-asc':
                                                                                                                        return a.amount - b.amount;
                                                                                                                                case 'date-desc':
                                                                                                                                          return new Date(b.date) - new Date(a.date);
                                                                                                                                                  case 'date-asc':
                                                                                                                                                            return new Date(a.date) - new Date(b.date);
                                                                                                                                                                    default:
                                                                                                                                                                              return new Date(b.date) - new Date(a.date);
                                                                                                                                                                                    }
                                                                                                                                                                                        });

                                                                                                                                                                                          return (
                                                                                                                                                                                              <div className="card">
                                                                                                                                                                                                    <h2>Expense History</h2>
                                                                                                                                                                                                          
                                                                                                                                                                                                                {/* Filters */}
                                                                                                                                                                                                                      <div className="filters">
                                                                                                                                                                                                                              <div className="filter-group">
                                                                                                                                                                                                                                        <label>Category</label>
                                                                                                                                                                                                                                                  <select
                                                                                                                                                                                                                                                              value={filters.category}
                                                                                                                                                                                                                                                                          onChange={(e) => onFilterChange('category', e.target.value)}
                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                <option value="">All Categories</option>
                                                                                                                                                                                                                                                                                                            {categories.map(category => (
                                                                                                                                                                                                                                                                                                                          <option key={category} value={category}>{category}</option>
                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                </select>
                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                <div className="filter-group">
                                                                                                                                                                                                                                                                                                                                                                          <label>From Date</label>
                                                                                                                                                                                                                                                                                                                                                                                    <input
                                                                                                                                                                                                                                                                                                                                                                                                type="date"
                                                                                                                                                                                                                                                                                                                                                                                                            value={filters.startDate}
                                                                                                                                                                                                                                                                                                                                                                                                                        onChange={(e) => onFilterChange('startDate', e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="filter-group">
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <label>To Date</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  type="date"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              value={filters.endDate}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onChange={(e) => onFilterChange('endDate', e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="filter-group">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <label>Sort By</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <select
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    value={sortBy}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onChange={(e) => onSortChange(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <option value="date-desc">Newest First</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <option value="date-asc">Oldest First</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <option value="amount-desc">Highest Amount</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <option value="amount-asc">Lowest Amount</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* Expense List */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="expense-list">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {filteredExpenses.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="empty-state">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p>No expenses found. Add your first expense to get started!</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        filteredExpenses.map(expense => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div key={expense.id} className="expense-item">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="expense-info">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h4>{expense.category}</h4>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p>{expense.description || 'No description'}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <small>{new Date(expense.date).toLocaleDateString()}</small>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="expense-amount">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ${expense.amount.toFixed(2)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="expense-actions">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="btn btn-edit btn-sm"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onClick={() => onEdit(expense)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Edit
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="btn btn-danger btn-sm"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onClick={() => onDelete(expense.id)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Delete
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              export default ExpenseList;